first stab at reworked class init, which separates class registration/class object creation from class init, and checks during ClassInfo.getClassInfo() if all required classes can be resolved, throwing a NoClassInfoException otherwise (this includes all baseclasses and interfaces). This can cause quite some refactoring in clients that were not prepared to handle such exceptions, but we need to pass this error on to where it can be handled - in most cases this has to be turned into a NoClassDefFoundError inside the application